name = "bc"
compatibility_date = "2024-11-01"

# Tell Cloudflare Pages where your static site lives
pages_build_output_dir = "cloudflare/html"

# Keep your D1 binding for the project
[[d1_databases]]
binding = "DB"
database_name = "bestiedb"
database_id = "7ccf7968-cb51-4001-a81b-ca235b8d2403"
